services:
  eop:
    build: .
    volumes:
        - ./data:/foliage/data
    ports:
        - 8000:8000
    expose:
        - 8000:8000
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
